apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: template-directory
  description: this is a basic template directory
spec:
  targets:
    - ./scaffolder-templates/create-react-app/template.yaml
